uqbar-dao/uqbar-core

lib/zink/zink.hoon

Still need to support Nock %11 as a means of actually appending data into trace, but will do that separately.

zink: make crash-safe for all operations

---

tests/contracts/fungible.hoon

Adding a few test arms for %deploy, %set-allowance, and %mint

Adding test arms for fungible.hoon

---

lib/uqbar.hoon

uqbar/zane: fix scry arm in lib

---

lib/merk.hoon

merk: added +uni, +dif, and +bif and made +mer calls more terse

---

app/wallet.hoon
lib/wallet/parsing.hoon
lib/wallet/util.hoon
mar/zig/wallet-poke.hoon
mar/zig/wallet-update.hoon
sur/wallet.hoon

Small PR to get the wallet updates for frontend working properly. Also adds a subscription path for frontend to receive metadata-store.

fixes for frontend parsing

---

app/uqbar.hoon
gen/sequencer/init.hoon
sur/uqbar.hoon

```
:uqbar &uqbar-action [%ping ~]
```
triggers pinging of indexers, starting 5s from now, ending within 30s from then.

uqbar: add ping action

---

app/uqbar.hoon

* not really used until remote scry since all users must run an %indexer
* adds fragility

uqbar: comment out fallback logic

---

app/uqbar.hoon
app/wallet.hoon
lib/wallet/util.hoon

uqbar.hoon needs to unsubscribe from indexer when it gets unsubbed from by an app, otherwise you don't get that crucial first update

fix wallet unsub

---

app/uqbar.hoon
app/wallet.hoon
sur/wallet.hoon

Reverts uqbar-dao/ziggurat#190
See discussion therein

Revert "wallet: sign as scry"

---

lib/ziggurat.hoon

ziggurat: fix simple gall app cord

---

readme.md

readme: repair-deploy-instructions

---

app/ziggurat.hoon
mar/ziggurat/project-update.hoon

Changed data-text to noun-text

---

app/indexer.hoon
app/sequencer.hoon
lib/zig/indexer.hoon
lib/zig/wallet.hoon
readme.md
sur/zig/indexer.hoon
sur/zig/sequencer.hoon

```bash
$ curl --cookie "$NEC_COOKIE" localhost:8083/~/scry/indexer/json/hash/0xc478.23f9.2f67.7a47.c9c4.e118.34eb.e4f4.json | jq
...
"transactions": [
{
"output": {
"errorcode": 0,
"gas": 18855,
"events": [],
"burned": {},
"modified": {
"0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6": {
"label": "account",
"source": "0x74.6361.7274.6e6f.632d.7367.697a",
"salt": 1936157050,
"is-data": true,
"noun": {
"account": {
"balance": 299999999999999900000,
"metadata": "0x61.7461.6461.7465.6d2d.7367.697a",
"nonce": 0,
"allowances": {}
}
},
"id": "0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6",
"holder": "0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70",
"town": "0x0"
}, …
```

indexer: store and serve `processed-txs:seq`

---

app/indexer.hoon
sur/zig/indexer.hoon

```bash
$ curl --cookie "$NEC_COOKIE" localhost:8083/~/scry/indexer/json/item-transactions/0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6.json | jq
{
"transaction": {
"0x7029.8459.ed3a.9305.6230.f98c.cae3.b4d3": {
"location": {
"transaction-num": 0,
"batch-id": "0xc478.23f9.2f67.7a47.c9c4.e118.34eb.e4f4",
"town-id": "0x0"
},
"transaction": {
"shell": {
"status": 0,
"contract": "0x74.6361.7274.6e6f.632d.7367.697a",
"budget": 1000000,
"eth-hash": null,
"rate": 1,
"town-id": "0x0",
"caller": {
"id": "0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70",
"nonce": 1,
"zigs": "0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6"
}
},
"calldata": {
"give": {
"to": "0xd6dc.c8ff.7ec5.4416.6d4e.b701.d1a6.8e97.b464.76de",
"amount": …
```

indexer: add `%item-transactions`

---

app/rollup.hoon
app/sequencer.hoon

Fix first batch root being double-recorded

---

readme-pyro.md

FYI @dr-frmr @0x70b1a5 @willbach

pyro,ziggurat: add readme

---

app/sequencer.hoon

Remove super annoying assertion that's not useful anymore.

Sequencer: allow pokes from anyone

---

con/lib/fungible-interface-types.hoon
con/lib/zigs-interface-types.hoon

Adjust the JSON interfaces for our fungible token contracts to accomodate recent change to nonce storage.

Update fungible token json interfaces

---

readme.md

looks like this file moved, but the path hasn't been update in the readme yet

readme: update a dojo command for building indexer molds

---

.gitattributes
app/ziggurat.hoon
lib/py/pill.pill
readme-pyro.md
sur/zig/ziggurat.hoon
zig/test-steps/send-nec-addresses.hoon
zig/test-steps/send-nec-custom.hoon
zig/test-steps/send-nec.hoon

ziggurat: cache %ca scries

---

app/wallet.hoon

Feature for new-user convenience

wallet: auto-populate with seed phrase on install

---

desk.docket-0

**Problem**:
Releasing 0.0.10 today
**Solution**:
Update version number in desk.docket-0
**Notes**:

update version number for release 0.0.10

---

zig/custom-step-definitions/deploy-contract.hoon
zig/custom-step-definitions/poke-wallet-transaction.hoon
zig/custom-step-definitions/scry-indexer.hoon
zig/custom-step-definitions/send-wallet-transaction.hoon

Accompanies https://github.com/uqbar-dao/dev-suite/pull/36

zig: make custom-step-definitions return configs

---

zig/configs/zig.hoon
zig/state-views/agent/wallet-metadata-store.hoon
zig/state-views/agent/wallet-our-items.hoon
zig/state-views/chain/chain.hoon
zig/state-views/chain/holder-our.hoon
zig/state-views/chain/source-zigs.hoon
zig/state-views/chain/transactions.hoon

Paired with https://github.com/uqbar-dao/dev-suite/pull/38

zig: add default state views

---

gen/brass.hoon
lib/pill.hoon

**Problem**:
We have our own subfolders within desks, so need a way to make pills that include these desks
**Solution**:
I've been doing this ad-hoc when I need to make a pill, but good to have included in the repo: a custom pill.hoon and brass.hoon to make brass pills.

Add functionality to build custom pills

---

zig/custom-step-definitions/deploy-contract.hoon

For use with https://github.com/uqbar-dao/dev-suite/pull/44

zig: use updated test-globals

---

lib/docket.hoon
lib/mip.hoon
mar/docket-0.hoon
sur/docket.hoon
sur/hark-store.hoon
sur/settings.hoon

**Problem**:
System files were moved around in recent update, and our symlinks were broken.
**Solution**:
Update symlinks to new locations

fix old symlinks

---

lib/zig/sys/engine.hoon
sur/zig/engine.hoon

**Problem**:
Special withdraw transaction not aligned to goerli contract yet, needs changes
**Solution**:
The new mold and data in this PR

Enable uETH withdraws

---

app/wallet.hoon
desk.docket-0
mar/wallet/poke.hoon
mar/wallet/thread-update.hoon
sur/zig/wallet.hoon
ted/get-address-from-ship.hoon

**Problem**:
<A brief description of the problem, along with necessary context.>
**Solution**:
<A brief description of how you solved the problem.>
**Notes**:
<Any other information useful for reviewers.>

latest from master

---

desk.docket-0

**Problem**:
The UI for sending transactions was showing an alert erroneously.
**Solution**:
Fixed the form to not require a "from" address if there is a token selected
**Notes**:
None

Fix for sending token txns

---

app/batcher-interval.hoon

**Problem**:
%batcher-interval doesn't compile -- which interferes with dev-suite installation of master since it compiles all apps.
**Solution**:
Fix bugs.
**Notes**:
None

batcher-interval: get compiling again

---

desk.docket-0

includes fixes for indexer, hardware wallets

glob 0.1.7

---

lib/transaction-sim.hoon

often need private keys to test signing with.

add privkeys in transaction sim lib

---

app/wallet.hoon
lib/zig/wallet.hoon

we should do this with transactions too, currently we aren't hashing transactions that have been signed with eth wallets. 
initial version with typed-signatures

eth-maxxing signatures

---

desk.docket-0

**Problem**:
Changes to transaction signing require frontend changes
**Solution**:
Signing updates for the UI on this branch: https://github.com/uqbar-dao/uqbar-core-ui/tree/signing-updates
**Notes**:
None

UI v0.1.9-2
