app/sequencer.hoon
app/ziggurat.hoon

Fixes faulty arguments being passed into `+read-rice` and `read-wheat` respectively in the `on-peek` arms of both agents that use it. The util arms expect the path to be without the leading `%x` that is present in the path from the scry.

sequencer/ziggurat: fix `read-rice`/`read-wheat` callsites

---

app/indexer.hoon

Had messed up the logic in `+are-updates-same` by trying too hard, so diffs weren't getting sent to subscribers.
I'd advise reviewing this PR by looking at the commits separately: the first commit, eecb96d, is a pure refactor: just moving some code closer to the call sites and fixing some whitespace. The second commit, e3c3885, is the fix.

indexer: fix `+are-updates-same`

---

app/indexer.hoon

Two fixes, first to expand the scope of what `/hash` returns to be more in line with expectations, and second, to return the most recent `grain` with a given `id` upon a scry.
The `/hash` scry is supposed to return everything associated with the given hash. Therefore, it should also return the `/lord` and `/holder` results; 54c1910 makes this the case.
In changing the `update` types for `%grain` to `map` from `set` a change from returning the entire history of a `grain` to returning just a single element was also made (since older versions of the `grain` will share an `id`). The bug is that the most recent `grain` is not returned, but instead some past version since we store pointers to `grain`s in `jug`s, and the `set`s within `jug`s are not ordered by recency.
For indexing we have to …

indexer: fix hash scry and scry latest state

---

lib/zig/mill.hoon

Without this, starting a testnet fails when running `|install our %zig`
cc @dr-frmr

mill: comment out zink printf causing compilation fail

---

lib/zig/mill.hoon

Quick change to make sure `salt`s are immutable on `rice` (@ynx0 reminded me that this behavior is important and should be enforced) and that the type of a grain is not being swapped in a change event.

Mill: add salt and type checks to changed grains in +harvest

---

app/indexer.hoon
sur/indexer.hoon

As per @willbach request: a scry/subscription to allow querying of all `egg`s/transactions a `rice` was involved in.

indexer: add `%grain-eggs` scry, subscribe, index

---

lib/zig/contracts/fungible.hoon

%take tests were throwing an underflow error. Removed what appeared to be a redundant jab:by causing the allowance amount to be subtracted twice. This now matches the %take code in zigs.hoon which has already been tested

Remove redunant jab:by from %take

---

lib/zink/pedersen.hoon

This goes with https://github.com/martyr-binbex/urbit/tree/mb/local-jet to wire up the pedersen jet to our local pedersen hash. It's temporary until the jet and hash are released in the main urbit repo.

wire pedersen jet to local arm

---

gen/sequencer/init.hoon

Was trying to play with zink/zock today and so updated `gen/sequencer/init.hoon` to work with new types. I have elided `interface` and `types` from `wheat`s.

sequencer: update `:sequencer|init` to work with new types

---

lib/merk.hoon
lib/zig/sys/smart.hoon

Ended up being useful during debugging. Adapted from `key:by` so it should be correct.

merk: add `+key` to `bi`

---

lib/zig/mill.hoon
sur/mill.hoon
tests/lib/mill-2.hoon

Finally, burns will be real. With this addition to `mill`, one can submit a special `%burn` transaction to a sequencer.
The burner must be either `holder` or `lord` of the grain in question.
A burn transaction is marked by setting the `to` contract ID to `0x0` and the action to `[%burn {id} {town-id}]`, where {id} is of the grain in question, and {town-id} is the town the burned grain is destined for.
Burns done this way produce an event noting the burn.
What else needs to be added here? So far, we're just creating the burn -- the "reconstitute" transaction will come later, as we're waiting to see how to gather that information from the rollup. Burns will be one-way until then!

Add asset escape hatch to `mill`

---

lib/ziggurat.hoon
lib/zink/conq.hoon

Change conq.hoon and lib/ziggurat.hoon to make contract compile errors that match enough, such that ziggurat frontend can parse line numbers and red-squiggly-underline the site of error.

Slightly better compiler errors

---

app/uqbar.hoon

Remove from `indexer-sources-ping-results` on `%remove-source` and `%set-sources` more precisely.
Not sure this was the bug you were seeing, but it is certainly better than how we were previously doing it @dr-frmr

uqbar: only remove removed sources

---

app/indexer.hoon
app/wallet.hoon
ted/watch-indexer.hoon

With `jold`s, scrys can be prepended with `/json` in order to have the output be JSON and the data/actions of grains/eggs be molded with the `lord`s `interface`/`types`. This PR adds a similar prepend option to subscriptions.

indexer: add `/json`-prepended subscription paths

---

app/indexer.hoon
readme.md
sur/indexer.hoon

The point of this fix, aside from increasing robustness, is that we want to switch the order of `%indexer-catchup` with `%set-sequencer` and `%set-rollup` to avoid a situation where:
1. New user runs `%indexer-catchup`.
2. While they are catching up, some number of new batches come out.
3. User subscribes to sequencer and rollup.
4. End result: user is missing some batches.
What is happening is that `%indexer-catchup` was not acting on a null state, and so, since the sequencer and rollup will give us current state upon subscribe, the most recent batch will incorrectly appear in the first batch.
To see bug on master:
```
::  on ~zod
::  setup
:rollup|activate
:sequencer|init our 0x0 0xc9f8.722e.78ae.2e83.0dd9.e8b9.db20.f36a.1bc4.c704.4758.6825.c463.1ab6.daee.e608
:indexer &set-sequencer …
```

indexer: ensure catchup to proper state

---

app/indexer.hoon
readme.md

Second-order indices store a hash of the underlying item they reference. For example, `holder-index` stores a `grain-id`, so that when a user queries for grains held by `0xdead.beef`, `holder-index` can look up all the `grain-id`s and those `grain`s can then be returned.
This runs into a problem when `grain`s can change `holder`s but keep the same `grain-id`. A subscriber to `/holder/0xdead.beef` will continue to hear about changes to the NFT grain `0xcafe.babe` even after `0xcafe.babe` has been traded to someone else.
To solve this problem, we added a filter. First, query the `holder-index` and get all those `grain`s that at one time were held by `0xdead.beef`. Second, check each of those `grain`s to see if they still have `=(0xdead.beef holder.p.grain)`.
This introduces a second …

indexer: fix `/holder` subscription

---

lib/zig/contracts/lib/zigs-interface-types.hoon

`mill` currently gives back zigs `%give` transactions to the chain without the `budget` field. This will be fixed Soon, but until then, hack the zigs `%give` interface to agree with the current output.
```json 
"0x61.7461.6461.7465.6d2d.7367.697a": {
"label": "token-metadata",
"salt": 1936157050,
"lord": "0x74.6361.7274.6e6f.632d.7367.697a",
"data": {
"token-metadata": {
"name": "UQ| Tokens",
"salt": "0x7367.697a",
"deployer-address": "0x0",
"decimals": 18,
"cap": null,
"minters": null,
"symbol": "ZIG",
"supply": 1e+26,
"mintable": false
}
},
"id": "0x61.7461.6461.7465.6d2d.7367.697a",
"is-rice": true,
"holder": "0x74.6361.7274.6e6f.632d.7367.697a",
"town-id": "0x0"
},
"0x222f.e9fd.ba8c.98ee.79f3.a2b6.2088.f319.2235.957f.807e.6a86.75e4.e095.1b08.6a03": {
"label": "account",
"salt": …
```

indexer: hack zigs `interface` to agree with mill zigs %give output

---

app/wallet.hoon
lib/merk.hoon
lib/zig/sys/smart.hoon
lib/zink/zink.hoon
sur/zink.hoon

Using SHA hashing instead of the very slow Pedersen hash in order to make execution-only testnet operable in a performant way with no extra jets.

swap shag to sham

---

app/wallet.hoon

I ran into this problem in %indexer as well: not sure why *_foo doesn't give you bunted type as expected.

wallet: reset keys in %import-seed and %generate-hot-wallet

---

app/faucet.hoon
sur/faucet.hoon

This PR changes %faucet state, so we'll have to |nuke %faucet and re-instantiate. This is okay for mass-distribution, since %faucet is not in the `desk.bill` of our distribution.

Add exponential backoff to %faucet rate-limiting

---

app/uqbar.hoon
app/wallet.hoon
sur/wallet.hoon

I think this is a way better interface for signing messages using keys stored in the wallet. I'm using this functionality in a subscription-gating project over [here](https://github.com/hosted-fornet/whitelist/pull/3). I like the `%sign-message` path best, but left the other in as well in case there is something I was missing about why typed messages are so special -- it seems to me that the serialization of the message should be up to the user, not the wallet to decide.
What do you think? @dr-frmr @tadad 
For reference, the previous way to do this is a poke [here](https://github.com/uqbar-dao/ziggurat/blob/cd771fb1b79acbccb9c4ae0a62daed8e83bc8088/app/wallet.hoon#L189-L202), followed by a scry to look at `signatures` stored in state. Unless there is some reason to keep the signatures …

wallet: sign as scry

---

app/indexer.hoon

Fix bug introduced in PR #170 for `/batch-order` subs. That PR added a new requirement for subscriptions: that a random string be appended to subscription paths (though `/history` is the trumping appendend, i.e. the last element). However, `/batch-order` subscriptions had been treated as a special case in the code, and were not properly updated to the new system, so that subscription updates would be incorrectly served to, e.g., `/batch-order/0x0` rather than `/batch-order/0x0/0xdead.beef`.
The present PR handles `/batch-order` subscriptions the same way as others so that the subscriptions are served to the properly disambiguated paths.
To test, send a tx from a fakeship. On master, the wallet balance (viewed via `:wallet +dbug`) will not update, but here it will.

indexer: fix batch-order subs

---

app/indexer.hoon
sur/indexer.hoon

Remove state transition logic from %indexer since we are going to make a new testnet with breaking changes.
Another PR will remove the majority of the subscription logic from %indexer, and may also alter the state, since `old-sub-updates` and `old-sub-paths` will no longer be needed for tracking subscription diffs. I'll try to have that included in the breaking changes -- if I can't get it done in time, it will be the new `state-1`.

indexer: remove state transition logic

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
mar/ziggurat/action.hoon
mar/ziggurat/project-update.hoon
sur/zig/ziggurat.hoon

FYI @willbach @0x70b1a5 should work now. If there are other pokes not working, let me know and I'll add them here. I specifically tested:
```hoon
:ziggurat &ziggurat-action [%foo %new-project 0x1234.5678]
:ziggurat &ziggurat-action [%foo %populate-template %nft [0xdead.beef.cafe 0xcafe.babe 0xcafe.babe 0x0 `@`%nft-metadata %token-metadata '[%foonft %foo (make-pset `(list @tas)`~[%hat %eyes]) 1 ~ %.y ~ 0x1234.5678 `@`%foonft-salt]']]
```
and bash equivalents:
```bash
curl --cookie "$NEC_COOKIE" --header 'content-type: application/json' -X PUT localhost:8083/~/channel/1 --data '[{"id": 1, "action": "poke", "ship": "nec", "app": "ziggurat", "mark": "ziggurat-action", "json": {"project": "foo", "action": {"new-project": {"user-address": "0x1234.5678"}}}}]'
curl --cookie "$NEC_COOKIE" --header …
```

ziggurat: fix `%ziggurat-action` json `+grab`

---

app/indexer.hoon
app/sequencer.hoon
app/uqbar.hoon
app/wallet.hoon
lib/zig/indexer.hoon
lib/zig/wallet.hoon
mar/wallet/update.hoon
sur/zig/engine.hoon
sur/zig/indexer.hoon
sur/zig/sequencer.hoon
sur/zig/uqbar.hoon
sur/zig/wallet.hoon

Get rid of `txn`: now mostly use `transaction`, with a few `tx` when shorter name required.
Get rid of `root` in `%indexer`. Now use `batch-id` everywhere user-facing, with a few `root` references when interfacing with other Uqbar apps that use that term.

indexer: refactor some names

---

ted/upgrade.hoon

This will be part of `release-0.0.5` in order to have users nuke their app states in order to download `next/smart`

Add app-upgrade thread to master

---

app/indexer.hoon

@hosted-fornet: this change is designed to slot into release-0.0.5, in order to remove the issue of incompatible updates along subscription paths between the bacdun sequencer and people with the suite installed.
I've tested this on moons, and here's what seems to work for a smooth upgrade:
1. release-0.0.5 is sent out for OTA with this PR included
2. users install the OTA without issue
3. ~bacdun has all app states wiped and manually upgrades to release-0.0.6 (which will contain `next/smart`)
4. ~bacdun starts a fresh chain, turns on batching, faucet etc
5. release-0.0.6 is sent out for OTA
At any time after step 5, users can run this:
```
-zig!upgrade
|install ~dister-dozzod-bacdun %zig
```
This will nuke their 0.0.5 app states and begin install of 0.0.6, which will initially fail to …

indexer: become inert on kick

---

lib/zig/sys/engine.hoon

The line here was causing immutable contracts deployed through publish.hoon to fail validation. This was because we were checking the pact ID against the source, which was the ID of publish.hoon, but should be `0x0` in immutable contracts! Easy fix.

engine: fix validation check for issued pacts

---

app/indexer.hoon
ted/upgrade.hoon

For `release-0.0.6`: %indexer should return to resubbing on kick, and upgrade thread is no longer needed. Don't want people accidentally nuking all their app states, so we will make the thread inert until a future time when it may be needed again.

indexer: make subscriptions resub on kick again, upgrade: make thread inert

---

app/indexer.hoon

If we get a bunted timestamp, fill it in with `now.bowl`. This means that different users' %indexers may disagree on block timestamps.
The bunted times are coming from [here](https://github.com/uqbar-dao/uqbar-core/blob/master/app/rollup.hoon#L58). If we want a similar behavior to this PR, we could have the %rollup assign its `now.bowl` rather than sending a bunted value.
Alternatively, to increase canonicity of block timestamps, we could store in state of %rollup a `most-recent-batch-times=(map town-id=@ux most-recent-timestamp=@da)`. Then, `+on-watch`, we would hand back
```hoon
[%sequencer-rollup-update !>(`town-update`[%new-peer-root id (rear roots.hall) (~(gut by most-recent-batch-times) id *@da)])]
```
This would involve a change in state, so perhaps we should queue this up on …

indexer: fill in bunted time with `now.bowl`

---

app/wallet.hoon

Tested, working, no change to anything except wallet pending txns now have nonces equivalent to the size of the pending map. ~~This does have the potential for overlapping txn hashes, in a situation where two identical transactions are entered one after another, but with a third txn being signed and submitted between their entries. ~~
Edit: made better by just using `eny.bowl`

wallet: add ephemeral nonces to pending txns

---

lib/zig/indexer.hoon

Addresses #304 by virtualizing the `jold` call so that malformed data does not crash, and instead gives the default "un-jolded" output.

indexer: virtualize jold to avoid crashing on malformed data

---

app/faucet.hoon
app/wallet.hoon
lib/zig/sys/engine.hoon
lib/zig/wallet.hoon
mar/wallet/frontend-update.hoon
mar/wallet/poke.hoon
readme.md
sur/zig/wallet.hoon

The purpose of this PR is to add a scheme to the wallet agent where apps can be notified of completed transactions that they initiated. I'm actively using it in %pokur where this behavior is very necessary.
I considered routing these pokes through %uqbar but it actually doesn't make a difference because the receiving app does not yet have a way in gall to distinguish the "source app". So it just doesn't matter and I'll keep them going straight from %wallet. If this changes in the future will app sandboxing we can update then.
This is a breaking change to %wallet agent state so it's going to `next/smart`

Wallet: provide responses to apps that build transactions and send through us

---

lib/zig/sys/engine.hoon

This came up when performing a zigs %give from a contract inside a continuation call. Since the initial transaction caller pays the budget for all continuation calls, the budget should not be a part of the zigs token transfer validation in the contract. To nullify that line of logic in the contract, we can just set the field to 0 in the engine.
In the future I want to remove the budget field from zigs contract entirely if possible, and do all this logic in the engine.

Engine bugfix: don't enforce budget on zigs transactions that are part of continuation calls

---

sur/zig/engine.hoon
sur/zig/sequencer.hoon

Inspired to do this because it drastically reduces the number of files other desks need to copy in to interact with wallet and indexer!

sur/engine: remove unnecessary import

---

app/wallet.hoon
lib/zig/wallet.hoon
sur/zig/wallet.hoon

We're adding batch IDs to the update that wallet gives on transaction completion. This will allow other apps that build and track transactions to more effectively notify their peers. I was running into a bad race condition on %pokur where you'd notify the host about a new escrow transaction, but the host hadn't yet received the batch that contained the transaction. When it went to check relevant chain-data, it found nothing. 
You can imagine that a peer might actually be several batches behind. So, in situations like this you'll want to send the batch hash and have your peer wait until they're aware of that batch, then check your transaction.
(**state transition included and tested from 0.0.8, replacing current one in next/smart**)

wallet: add batch ID to %finished-transaction updates, for apps

---

app/faucet.hoon
app/uqbar.hoon
mar/uqbar/action.hoon
sur/zig/uqbar.hoon

This PR makes it so we can add a faucet UI to wallet. Since we track active sequencers in uqbar.hoon, it makes the most sense to attach this poke there -- sequencers will usually host faucets, and if this changes, uqbar.hoon should track faucet hosts. 
Tested on fakeships, will need to build usage into wallet FE.

uqbar.hoon: add a poke to open faucets

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
mar/ziggurat/action.hoon
readme-pyro.md
sur/zig/ziggurat.hoon

for use with frontend.
expectation is more developed tests can be imported from files using what has been retitled `%add-test-file`.
these can also be editing using the standard text editing UI or an external text editor.
during development, can have a pane where user can write in `test-steps` for more integrated initial development
Still TODO: add another poke to `%save-test` to convert a test into a file and save it in the project dir.

ziggurat: re-add `%add-test` with `test-steps`

---

pull_request_template.md

**Problem**:
We don't have a standardized way to communicate what a PR is solving and how we solved it.
**Solution**:
Add a PR template. The template proposed in d110c37 is concise but gives an outline for a PR description that can be very helpful for reviewers to understand a PR.
**Notes**:
See docs for discussion of how Github does PR templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
FYI @0x70b1a5 @tadad @willbach : let me know if you have any comments. Is this useful? A waste of time? Would a different template be better?

add pull request template

---

app/pyro.hoon
app/ziggurat.hoon
gen/pyro/stop.hoon
lib/zig/pyro.hoon
mar/pyro/action.hoon
mar/pyro/update.hoon
sur/zig/pyro.hoon
ted/ziggurat/test/run.hoon

**Problem**:
Frontend cannot interact with %pyro.
**Solution**:
Rearrange %pyro and add `+enjs` and `+dejs` cores and appropriate `mar` files.
**Notes**:
~~WIP~~
I'll do a similar unification for %ziggurat scries/sub updates in #355 to reduce merge headaches.

pyro: rearrange pokes; allow FE pokes

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
sur/zig/ziggurat.hoon

**Problem**:
FE needs to be able to see what ships are running, according to %ziggurat.
**Solution**:
Add an update, scry path, and send updates for %pyro-ships-ready.
**Notes**:
FYI @0x70b1a5

ziggurat: add %pyro-ships-ready update and scry

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
sur/zig/ziggurat.hoon

**Problem**:
Current way to "edit" a test is to %delete-test and then %add-test, but this is not easy for FE.
**Solution**:
Add an %edit-test poke.
**Notes**:
None

ziggurat: add %edit-test

---

lib/zig/wallet.hoon

**Problem**:
When you derive a new address or add a tracked address, all of the tokens from all other wallets disappear.
**Solution**:
In the make-tokens arm, when the token scry for the new address is null (it will be the first in the list of addresses), the trap just escapes rather than iterating through the rest of the addresses. I changed the ?~ to continue to the $ recursion.

wallet: fixed ++  make-tokens bug

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
sur/zig/ziggurat.hoon

**Problem**:
FE needs to know what ships are currently syncing what desks/projects.
**Solution**:
Add a scry for the `sync-desk-to-vship` state.
**Notes**:
FYI @tadad

ziggurat: add %sync-desk-to-vship scry

---

gen/build-hash-cache.hoon
gen/compile.hoon
lib/zig/ziggurat.hoon
lib/zink/conq.hoon

**Problem**:
When compiling contracts, we do not get a useful stack trace.
**Solution**:
Change the hoon parser from `vast` to `(vang & pax)` to give stack trace on failure; various minor changes to get paths to the right place.
**Notes**:
See https://github.com/urbit/urbit/blob/develop/pkg/arvo/sys/vane/clay.hoon#L1062 and https://github.com/urbit/urbit/blob/develop/pkg/arvo/sys/hoon.hoon#L11419-L11421 for how I tracked this down.

conq: change `vast` -> `vang` to get stack trace on contract compilation

---

app/ziggurat.hoon
gen/build-hash-cache.hoon
gen/compile.hoon
lib/zig/ziggurat.hoon
lib/zink/conq.hoon
ted/ziggurat/test/run.hoon

**Problem**:
Compiler errors for test-steps, custom-step-definitions, configuration files are uninformative at best.
**Solution**:
Use `vang` to replace `vast`, as in #391 
Remove some old code that was trying to improve the bad situation but is no longer necessary now that we have real stack traces.
**Notes**:
This PR brings in #391 as well as some other changes. More compiler improvements to come, but I want to keep this fairly tightly scoped. This PR is working but I want to wait to review/merge it until #391 is merged so we can bring in any changes from there to here. If that PR is slow to merge I may change my mind.

ziggurat: improve compiler errors with vang

---

app/batcher-interval.hoon
app/faucet.hoon
app/indexer.hoon
app/rollup.hoon
app/sequencer.hoon
app/uqbar.hoon
app/wallet.hoon

**Problem**:
Need to reduce verbosity for user-installed core
**Solution**:
Removing `verb` from all core apps + commenting out non-useful dojo prints.

Release 0.1: remove excess prints, turn off verb for all apps

---

app/uqbar.hoon
app/wallet.hoon
sur/zig/uqbar.hoon
sur/zig/wallet.hoon

**Problem**:
For a lot of the UX flows we want to provide, it's important to be able to ask another ship for their uqbar address. In any long term view, this will be done by a remote-scry, and later probably an on-chain directory. But we need a simple immediate solution for sharing an Uqbar address programmatically.
**Solution**:
I've added a new item to the wallet state, `share-prefs`:
```hoon
+$  share-prefs
$~  [%any ~]  ::  default
$%  [%one =address:smart]
[%any ~]
[%none ~]
==
```
This tracks which address you want to share when asked, if any. It defaults to `%any`, which means the wallet will just pop whatever address is on the top of your map and share it with the requester. If you don't want to do this, you can change your preferences with this poke:
```hoon
:wallet &wallet-poke …
```

Wallet: add a poke for sharing address

---

app/wallet.hoon
sur/zig/wallet.hoon

**Problem**:
Wallet doesn't pass on the tx-hash to app origin
**Solution**:
Include the hash in the wallet-update type
**Notes**:
.

wallet: add tx-hash to receipt

---

app/wallet.hoon
sur/zig/wallet.hoon

**Problem**:
Currently after poking wallet with %sign-typed-message, it's stored in state, and can be scried out with a hash of the typed-message afterwards. 
There's no confirmation from the user, no pending store, and no way for apps to poke and get a poke back for signed messages.
**Solution**:
Add origins to signed-messages pokes, and also add some user confirmation before signing/sending back signatures.
**Notes**:
WIP

wallet: add origin to %signed-message 

---

lib/zig/sys/engine.hoon

**Problem**:
Execution engine refactor made it so that +charge arm was not getting properly skipped if a transaction failed gas audit
**Solution**:
Check errorcode on transaction output before calling charge
**Notes**:
Deployed immediately to testnet

hotfix: engine: skip +charge on failed gas audit

---

app/indexer.hoon
app/sequencer.hoon
sur/zig/sequencer.hoon

**Problem**:
Sharing batch data from sequencer to indexers takes too long
**Solution**:
Use remote scry!

sequencer/indexer: switch to remote scry for batch sharing

---

app/wallet.hoon

In a contract context we use mostly petersen hashes, and the fungible, zigs, multisig contracts are using ++ recover from smart.hoon to recover a public key from a signed message and a signature.
Currently the wallet hashes the entire typed message with sham instead of shag.

wallet: sign typed messages with shag:smart instead of sham

---

lib/zig/sys/engine.hoon
ted/transaction-sim.hoon

**Problem**:
%validate calls *do* need scries, since otherwise it's quite impossible to build account contracts that can be non-hardcoded
**Solution**:
add search scry back into +abstract-combust
also, increased fixed gas limit to `30.000` to handle multisig -- can raise this further, too.

engine: add scries to abstract-combust

---

app/wallet.hoon
mar/wallet/poke.hoon
sur/zig/wallet.hoon

With account abstraction, we can have a contract pay gas and not sign or worry about signatures. Add a poke for it in wallet so other apps can use it and get back receipts. 
Could bake into the normal %transaction method and put in pending-store, but not pretty. 
Small error in on-agent jab py transaction store.

wallet: add %unsigned-transaction poke

---

app/wallet.hoon
lib/zig/sys/engine.hoon

when a tx gets signed from an external eth wallet, hash and verify it in engine too. 
this awaits some changes in UI to clean up the string that gets signed.
related with signed-type-messages: https://github.com/uqbar-dao/uqbar-core/pull/478
add tests to lib/engine [x]

engine: reproduce & validate eth-hashes for transactions
